spring:  
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/chandb
    username: root
    password: cometrue

token:
  expiration_time: 86400000
  secret: user_token_token_token
